I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/episodes/episode2.rpy", line 681, in script
    jump episode3
ScriptError: could not find label 'episode3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/episodes/episode2.rpy", line 681, in script
    jump episode3
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "D:\Programming\RenPy\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'episode3'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
ERAIDAproject 2.0
Mon Dec 19 21:51:28 2022
